version: '3'

tasks:
  build:
    desc: Build data-store [plugin]
    cmds:
      - go build -buildmode=plugin -o {{.ROOT_DIR}}/{{.PLUGINS_DIR}}/data-store.so {{.TASKFILE_DIR}}

  test:
    desc: Test data-store
    cmds:
      - go test -v {{.TASKFILE_DIR}}/...
