version: '3'

tasks:
  build:
    desc: Build lib1
    cmds:
      - go build -buildmode=plugin -o {{.ROOT_DIR}}/{{.PLUGINS_DIR}}/data-store.so .

  test:
    desc: Test lib1
    cmds:
      - go test -v ./...