version: '3'

tasks:
  build:
    desc: Build core
    cmds:
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/control-plane  ./cmd/main.go

  test:
    desc: Test core
    cmds:
      - go test -v ./...