version: '3'

tasks:
  build:
    desc: Build core
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/control-plane  {{.TASKFILE_DIR}}/cmd/main.go

  test:
    desc: Test core
    cmds:
      - go test -v {{.TASKFILE_DIR}}/...

