version: '3'

tasks:
  build:
    desc: Build api-gateway [plugin]
    cmds:
      - go build -buildmode=plugin -o {{.ROOT_DIR}}/{{.PLUGINS_DIR}}/api-gateway.so {{.TASKFILE_DIR}}

  test:
    desc: Test api-gateway
    cmds:
      - go test -v {{.TASKFILE_DIR}}/...
