[core]
listen_addr = ":50051"
api_endpoint = "control-plane.example.com:50051"

[core.tls]
cert_file = ".build/certs/server.crt"
key_file = ".build/certs/server.key"
ca_cert = ".build/certs/ca.crt"

[core.auth]
token_secret = "your-secure-secret"
token_duration = "24h"
ca_cert_path = ".build/certs/ca.crt"
ca_key_path = ".build/certs/ca.key"

[core.connection_params]
max_reconnect_delay = "60s"
keepalive_time = "30s"

[plugins]
path = ".build/plugins"
load = ["api-gateway", "data-store"]

[log]
level = "debug"
file = "logs/app.log"