version: '3'

includes:
  core: ./core/Taskfile.yml
  api-gateway: ./api-gateway/Taskfile.yml
  data-store: ./data-store/Taskfile.yml

vars:
  BUILD_DIR: .build
  PLUGINS_DIR: '{{.BUILD_DIR}}/plugins'

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  create-dirs:
    silent: true
    desc: Create build directories
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - mkdir -p {{.PLUGINS_DIR}}

  build-all-plugins:
    desc: 🔧 Building all plugin...
    deps:
      - api-gateway:build
      - data-store:build

  build:
    desc: Build everything
    deps: [create-dirs, build-all-plugins, core:build]

  build:proto:
    desc: Build the proto files
    cmds:
      - |
        protoc \
          --go_out=./shared/proto \
          --go_opt=paths=source_relative \
          --go-grpc_out=./shared/proto \
          --go-grpc_opt=paths=source_relative \
          -I ../proto \
          ../proto/*.proto

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  run:
    desc: Run core
    cmds:
      - ./{{.BUILD_DIR}}/control-plane

  run:dev:
    desc: Run core in development mode
    cmds:
      - ./{{.BUILD_DIR}}/control-plane -c ./config.dev.toml

  default:
    desc: Default task
    deps: [build]